Rails.application.routes.draw do
  post "/signup" => "users#signup"
  post "/login" => "users#login"
  post "/auto_login" => "users#autoLogin"
  post "/create_label" => "labels#createLabel"
  post "/get_labels" => "labels#getLabels"
  post "/create_post" => "posts#createPost"
  post "/get_posts" => "posts#getAllPosts"
  post "/get_post" => "posts#getPost"
  post "/update_post" => "posts#updatePost"
  post "/delete_post" => "posts#deletePost"
  post "/get_posts_by_labels" => "labels#getPostsByLabels"
  post "/post_comment" => "comments#postComment"
  post "/update_comment" => "comments#updateComment"
  post "/get_comments" => "comments#getComments"
  post "/delete_comment" => "comments#deleteComment"
end
